<?php 
/**
 * @property $data Shanty_Mongo_Document
 */

// download/get.json.phtml 


?>
<?php
if ($this->success) {
    $url = $this->url(array(
        'controller' => 'download',
        'id'         => $this->data->getId(),
    ), 'rest', true);
    
    $this->response->setHeader('Location', $url)
                   ->setHttpResponseCode(201);
    echo $this->json($this->data->__toArray());
    return;
}
echo $this->json($this->error);

